spring:
  application:
    name: scouter
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: false
  cors:
    allowed-origins:
      - http://localhost:5173
token:
  jwt:
    access-key: ThisIsLocalAccessKeyThisIsLocalAccessKey
    refresh-key: ThisIsLocalRefreshKeyThisIsLocalRefreshKey
    access-expired-hours: 1 # 1시간
    refresh-expired-hours: 336  # 14일
oauth2:
  google:
    client_id: scouter-google-client-id # REST API 키
    client_secret: scouter-google-secret-key # Client Secret 키
    redirect_uri: redirect-uri
    scope:
      - openid
      - https://www.googleapis.com/auth/userinfo.email
      - https://www.googleapis.com/auth/userinfo.profile
