spring:
  application:
    name: scouter
  jackson:
    serialization:
      write-dates-as-timestamps: false
  profiles:
    default: local
  config:
    import:
      - applicant-sync-mapping-data.yml
      - member-parse-mapping-data.yml
      - applicant-available-time-map.yml