#!/usr/bin/env bash
# MySQL(dev/prod 등)에서 데이터만 덤프해 로컬 H2용 SQL 파일을 만듭니다.
# (테이블은 애플리케이션 기동 시 JPA가 이미 만들므로 --no-create-info 권장)
#
# 사용 전: .env.local 에 DB_URL(jdbc:mysql://...), DB_USERNAME, DB_PASSWORD 설정
#   set -a && source .env.local && set +a
#   ./scripts/mysql-dump-for-local-h2.sh
#
# 출력: .local/h2-init.sql
# 로컬 실행:
#   SCOUTER_LOCAL_H2_INIT_SCRIPT=.local/h2-init.sql ./gradlew bootRun
#
# 주의: MySQL 전용 문법이 남으면 H2 RUNSCRIPT가 실패할 수 있습니다. 오류 나면 해당 구문을 수동으로 고치세요.

set -euo pipefail
cd "$(dirname "$0")/.."

if [ -z "${DB_URL:-}" ] || [ -z "${DB_USERNAME:-}" ] || [ -z "${DB_PASSWORD:-}" ]; then
  echo "DB_URL, DB_USERNAME, DB_PASSWORD 가 필요합니다 (.env.local 등)."
  exit 1
fi

url="${DB_URL#jdbc:mysql://}"
hostport="${url%%/*}"
db_and_query="${url#*/}"
database="${db_and_query%%\?*}"

if [[ "$hostport" == *":"* ]]; then
  host="${hostport%%:*}"
  port="${hostport##*:}"
else
  host="$hostport"
  port="3306"
fi

mkdir -p .local
out=".local/h2-init.sql"

echo "-- Generated by mysql-dump-for-local-h2.sh (data only, no DDL)" > "$out"
echo "SET MODE MySQL;" >> "$out"

mysqldump \
  -h "$host" -P "$port" \
  -u "$DB_USERNAME" -p"$DB_PASSWORD" \
  "$database" \
  --single-transaction \
  --quick \
  --set-gtid-purged=OFF \
  --skip-comments \
  --no-create-info \
  --skip-add-locks \
  --skip-disable-keys \
  --skip-set-charset \
  >> "$out"

# H2가 자주 거부하는 MySQL 덤프 줄 제거(필요 시 추가)
if command -v sed >/dev/null 2>&1; then
  sed -i.bak \
    -e '/^\/\*!40101 SET/d' \
    -e '/^\/\*!40103 SET/d' \
    -e '/^\/\*!40014 SET/d' \
    -e '/^\/\*!40000 ALTER TABLE/d' \
    -e '/^LOCK TABLES/d' \
    -e '/^UNLOCK TABLES/d' \
    "$out" && rm -f "${out}.bak"
fi

echo "작성됨: $out"
echo "다음으로 로컬 기동: SCOUTER_LOCAL_H2_INIT_SCRIPT=$out ./gradlew bootRun"
