-- DOCUMENT_ACCEPTED, INTERVIEW_ACCEPTED 추가
ALTER TABLE applicant
    MODIFY COLUMN state ENUM(
        'UNDER_REVIEW', 'DOCUMENT_ACCEPTED', 'DOCUMENT_REJECTED',
        'INTERVIEW_ACCEPTED', 'INTERVIEW_REJECTED', 'INCUBATING_REJECTED',
        'FINAL_ACCEPTED'
        ) NOT NULL;
