-- 면접 합격 시 바로 최종 합격 처리되어 INTERVIEW_ACCEPTED는 더 이상 사용되지 않으므로 제거
UPDATE applicant SET state = 'FINAL_ACCEPTED' WHERE state = 'INTERVIEW_ACCEPTED';

ALTER TABLE applicant
    MODIFY COLUMN state ENUM(
        'UNDER_REVIEW', 'DOCUMENT_ACCEPTED', 'DOCUMENT_REJECTED',
        'ASSIGNMENT_ACCEPTED', 'ASSIGNMENT_REJECTED',
        'INTERVIEW_REJECTED', 'INCUBATING_REJECTED',
        'FINAL_ACCEPTED'
        ) NOT NULL;
